baseURL = "http://jkhall.me/"
languageCode = "en-us"
title = "Detritus"

theme = "minimo"

Paginate = 5
preserveTaxonomyNames = true

pygmentsCodefences = "en"

defaultContentLanguage = "en"

[params.info]
description = "The thoughts and random musings of jordan hall"
title404 = "Nothing here!"

[params.assets]
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = ""

[params.copyright]
prefix = ""
holder = "JordanHall"
startYear = "2017"
suffix = ""

[params.settings]
dateFormat = "2006, Jan 02"
listDataFormat = "2006, Jan 02"
hideEntryNavigation = ["page"]
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false

[params.social]
github = "chiggachiggayeah"

[params.social.config]
platforms = ["github"]

[permalinks]
page = "/:slug/"

[languages]

[languages.en]
lang = "en"
languageName = "English"
weight = 1
